### ISSUE TITLE
proposal: auto detect docker or nerdctl runtime when not specified a runtime flag

### ISSUE THREAD

**Issue by zwpaper** [kubernetes-sigs/kwok#224]
### What would you like to be added?

1. change the runtime flag default to empty
2. auto detect by checking whether the docker/nerdctl executable file existed in PATH

I would like to implement it if accepted.

### Why is this needed?

nerdctl became more popular as a docker replacement, we have to specify the runtime args or add an env variable for nerdctl users.

it would be more convenience if we can detect it by ourself.

**Comment by wzshiming** [comment]
Thanks for the proposal, but I have a few questions about the proposal.
there are currently 4 runtimes, binary, docker, nerdctl and kind, is your idea to check only docker and nerdctl? 

> auto detect by checking whether the docker/nerdctl executable file existed in PATH

If just checking the binary is not reliable, a more reliable way to check if it is working properly is needed.

In my opinion, the binary runtime is a better choice than nerdctl for Linux, because it works in basically any environment, while nerdctl is required to be installed properly. WDYT?

**Comment by zwpaper** [comment]
Hi @wzshiming,

> there are currently 4 runtimes, binary, docker, nerdctl and kind, is your idea to check only docker and nerdctl?

I noticed that kind uses docker to pull images so I am assuming kind could only work when docker is available, it should also work when nerdctl is available by the way.

I recheck the code, and found out the kind executable file is also needed when specify as runtime, so it would also be necessary to check it at the same time.

all in all, kwok should check all 4 runtimes in order when no one is specified by users.
the only question is what should the order be.

> If just checking the binary is not reliable, a more reliable way to check if it is working properly is needed.

agree, checking the binary is the basic, checking if it is working properly would be better,
maybe we can run some basic command like `version`

> In my opinion, the binary runtime is a better choice than nerdctl for Linux, because it works in basically any environment, while nerdctl is required to be installed properly. WDYT?

partially agree, binary runtime is great and simple to use for Linux, but sometimes we want to keep the system clean, I would choose to use a container runtime than run it natively.

what's more, nerdctl is the only choice in macOS except for docker

**Comment by zwpaper** [comment]
by the way, I am using a mac to run kwokctl, and not yet found problems, I would submit a PR to update the docs about the macOS part later.

**Comment by wzshiming** [comment]
> I noticed that kind uses docker to pull images so I am assuming kind could only work when docker is available, it should also work when nerdctl is available by the way.

Kind only supports docker and podman, and does not support nerdctl.

> agree, checking the binary is the basic, checking if it is working properly would be better,
maybe we can run some basic command like version

nerdctl often seems to install successfully, but the container does not start due to incorrect installation of cni, etc.

> partially agree, binary runtime is great and simple to use for Linux, but sometimes we want to keep the system clean, I would choose to use a container runtime than run it natively.

On Binary runtime, the downloaded binary is stored in `~/.kwok/cache`, which is still very clean, [All-in-One Image](https://kwok.sigs.k8s.io/docs/user/all-in-one-image/) works this way.

**Comment by zwpaper** [comment]
> Kind only supports docker and podman, and does not support nerdctl.

Gocha, so that kind can only work when docker is available, so kwok should support custom driver check, and kind have to make sure docker working as expected.

> nerdctl often seems to install successfully, but the container does not start due to incorrect installation of cni, etc.

it is the user's responsibility to make sure nerdctl work, It is too hard to make sure everything works without problems, what kwok can do is try best to detect it.

> On Binary runtime, the downloaded binary is stored in ~/.kwok/cache, which is still very clean, [All-in-One Image](https://kwok.sigs.k8s.io/docs/user/all-in-one-image/) works this way.

that is personal tastes, right? and it also is why docker/nerdctl existed and kwok has docker and nerdctl driver.

I personally prefer using nerdctl to run envs like kwok cluster

**Comment by wzshiming** [comment]
I basically agree with your point about automatically detecting other runtimes when Docker is not available.
Actually, I'm a bit worried about Nerdctl because some of its features are not perfect, and there is a lot of hacked code in Kwokctl that it is compatible with.
So far we have only done full tests under binary and docker, and only tested that Nerdctl and Kind work, so we are a bit worried about its stability and consistency.

However, I think this enhancement is needed, but when adding it, we need to consider, the 5 runtimes, binary, docker, kind, nerdctl and podman, and make it configurable in KwokctlConfiguration in the order of detection.

**Comment by wzshiming** [comment]
I basically agree with your point about automatically detecting other runtimes when Docker is not available.
Actually, I'm a bit worried about Nerdctl because some of its features are not perfect, and there is a lot of hacked code in Kwokctl that it is compatible with.
So far we have only done full tests under binary and docker, and only tested that Nerdctl and Kind work, so we are a bit worried about its stability and consistency.

However, I think this enhancement is needed, but when adding it, we need to consider, the 5 runtimes, binary, docker, kind, nerdctl and podman, and make it configurable in KwokctlConfiguration in the order of detection.

**Comment by zwpaper** [comment]
I agree with you, I use nerdctl both in mac and linux, I could help to maintain the nerdctl compatibility and try to catch up without too many hacks

**Comment by wzshiming** [comment]
Thank you for your willingness to take on this work. 😄
