### ISSUE TITLE
[kwok] Respect HostNetwork of Pod

### ISSUE THREAD

**Issue by wzshiming** [kubernetes-sigs/kwok#284]
### What would you like to be added?

If `spec.hostNetwork` is true then `status.podIP` is set to `status.hostIP`.

### Why is this needed?

NONE

**Comment by swastik959** [comment]
@wzshiming can you please tell me about this issue more

**Comment by wzshiming** [comment]
@swastik959 Update details of the issue

**Comment by swastik959** [comment]
@wzshiming do i need to change https://github.com/kubernetes-sigs/kwok/blob/9ae9f320fdbf247ae1a1ec8fd7e9579cb68310af/pkg/kwok/controllers/pod_controller.go#L422

**Comment by wzshiming** [comment]
I expect the following changes

https://github.com/kubernetes-sigs/kwok/blob/8e2871ed268e8efbd3934eeb5432a9afe6844ac2/pkg/kwok/controllers/pod_controller.go#L466-L477

https://github.com/kubernetes-sigs/kwok/blob/8e2871ed268e8efbd3934eeb5432a9afe6844ac2/pkg/kwok/controllers/pod_controller.go#L420-L430

https://github.com/kubernetes-sigs/kwok/blob/5491b502b4ae22a4b2bd51d7b4b3a2ee8f0c864d/stages/pod-fast.yaml#L60

https://github.com/kubernetes-sigs/kwok/blob/5491b502b4ae22a4b2bd51d7b4b3a2ee8f0c864d/stages/pod-general.yaml#L97

**Comment by sunya-ch** [comment]
Very interesting. As I posted in the slack channel (#sig-scheduling), I made some modification to previous release v0.0.1 of kwok for testing the CNI operator that I'm working on. 
https://medium.com/@sunyanan.choochotkaew1/going-beyond-limits-scalability-test-ci-for-kubernetes-cni-operator-with-simulated-cluster-ed53e772dfa5

There, I did modify the pod_controller configurePod function.
And, in addition to that, I also made a mapping between hostName and hostIP and configure that.
The reason is that Pods are scheduled by (DaemonSet) controller and hostIP is set later (not manually set).

**Comment by wzshiming** [comment]
https://github.com/kubernetes-sigs/kwok/blob/122f36ce87128371d2b9bbcff43837d764b35e37/pkg/kwok/controllers/pod_controller.go#L126

It looks like we just need to change it to `func(nodeName string) string` and get the IP corresponding to the nodeName from the node_controller.

**Comment by Sajiyah-Salat** [comment]
Do we need to just change this

> https://github.com/kubernetes-sigs/kwok/blob/122f36ce87128371d2b9bbcff43837d764b35e37/pkg/kwok/controllers/pod_controller.go#L126
> 
> It looks like we just need to change it to `func(nodeName string) string` and get the IP corresponding to the nodeName from the node_controller.

or any further changes required.

**Comment by sunya-ch** [comment]
I think the point is the current node controller does not keep information of IP corresponding to the nodeName. 
In my understanding of the code, we need to add that mapping in the node controller watch and pass that mapping to the pod controller. We also need to be careful of map read/write concurrency because it might be multiple threads access that map (from node controller and pod controller).   

( Another way is connecting to API server to get node information when configuring pod but I may not recommend this way because it will cause one extra communication to API server which does not exist when there is a kubelet process. )

I have already implemented some changes to solve this issue modified from v0.0.1. Although there are multiple changes in latest version but the significant points to solve this issue are the same as much as I see. I can work on this with some additional effort on rebasing.

**Comment by wzshiming** [comment]
@sunya-ch 
Looks good, with the addition that we should use a structure and perhaps support `CIDR` #78 or `Dual Stack` in the future.
